import {
  app,
  Menu,
  nativeImage,
  Tray,
  dialog,
  BrowserWindow,
  ipcMain,
  clipboard,
} from "electron";
import * as path from "path";

import utils from "./utils";
import preferences from "./preferences";
import logger from "./logger";
import cacheUtils from "./inMemoryCache";
import tokenStorage from "./tokenStorage";

let tray: Tray | null = null;
let tokenWindow: BrowserWindow | null = null;

function showTokenWindow(token: string): Promise<void> {
  return new Promise<void>((resolve) => {
    tokenWindow = new BrowserWindow({
      width: 550,
      height: 520,
      frame: false,
      resizable: false,
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        preload: path.join(__dirname, "preload.js"),
      },
    });

    tokenWindow.loadFile("src/token.html");

    tokenWindow.webContents.on("did-finish-load", () => {
      tokenWindow?.webContents.send("token-received", token);
    });

    ipcMain.handleOnce("continue-with-token", async () => {
      logger.info("User clicked continue with token");
      tokenWindow?.close();
      return true;
    });

    tokenWindow.on("closed", () => {
      logger.info("Token window closed");
      tokenWindow = null;
      resolve();
    });
  });
}

function showTokenDialog() {
  const token = tokenStorage.getOrCreateToken();
  showTokenWindow(token);
}

function regenerateTokenDialog() {
  const result = dialog.showMessageBoxSync({
    type: "warning",
    title: "Regenerate Token",
    message: "Are you sure you want to regenerate the token?",
    detail:
      "This will invalidate the current token. You will need to update the token in your browser extension.",
    buttons: ["Cancel", "Regenerate"],
    defaultId: 0,
    cancelId: 0,
  });

  if (result === 1) {
    const newToken = tokenStorage.regenerateToken();
    cacheUtils.setToken(newToken);
    showTokenWindow(newToken);
    logger.info("Token regenerated by user");
  }
}

function copyTokenToClipboard() {
  const token = tokenStorage.getOrCreateToken();
  clipboard.writeText(token);
  dialog.showMessageBox({
    type: "info",
    title: "Token Copied",
    message: "Token copied to clipboard!",
    detail: "Paste this token in your Thunderclone browser extension settings.",
  });
}

function setupTray() {
  const icon = nativeImage.createFromPath(path.join(__dirname, "icon.png"));
  console.log("app ready", icon, app.getPath("appData"));
  tray = new Tray(icon);
  const contextMenu = Menu.buildFromTemplate([
    { label: "Start Service", click: utils.networking.startService },
    { label: "Stop Service", click: utils.networking.stopService },
    { type: "separator" },
    { label: "Show Token", click: showTokenDialog },
    { label: "Copy Token", click: copyTokenToClipboard },
    { label: "Regenerate Token", click: regenerateTokenDialog },
    { type: "separator" },
    { label: "Preferences", click: preferences.openPreferences },
    { label: "Quit", click: () => app.quit() },
  ]);
  tray.setToolTip("Thunderclone - Service Status: Stopped");
  tray.setContextMenu(contextMenu);
}

app.on("ready", async () => {
  logger.info("App ready event triggered");
  setupTray();
  try {
    // Get or create the authentication token
    const token = tokenStorage.getOrCreateToken();
    cacheUtils.setToken(token);

    // Show the token window to the user
    await showTokenWindow(token);

    logger.info("Starting service with authentication token");
    utils.networking.startService();
  } catch (error) {
    logger.error("Error during app initialization:", error);
  }
});

app.on("window-all-closed", () => {
  logger.info("All windows closed event triggered");
  if (process.platform !== "darwin") {
    // app.quit();
  }
});

app.on("will-quit", () => {
  logger.info("App will quit event triggered");
});

process.on("uncaughtException", (error) => {
  logger.error("Uncaught exception:", error);
  dialog.showErrorBox("An error occurred", error.message);
});
